### ISSUE TITLE
Approve MVPs

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/CA-Halloween-2021#1]
MVPs for all three missions are in a state I'd consider complete - take a look and if you agree, mark them green 🟢 and create Issues for their completion with each of the bullet-points made into a checklist box in the issue.

If you want to add, remove, shift points to/from iterations or otherwise alter the MVPs, then do so and assign this issue back to me - once we've got a two-way sign-off on an MVP we'll make an issue for it here and get to work.

https://github.com/Bubbus/CA-Halloween-2021/wiki/MVPs,-Part-1
https://github.com/Bubbus/CA-Halloween-2021/wiki/MVPs,-Part-2
https://github.com/Bubbus/CA-Halloween-2021/wiki/MVPs,-Part-3

**Comment by dgibso29** [comment]
Reviewed and approved MVP for all three. Looks good -- fairly low workload all things considered for MVP for the full event.

Create MVP root issues, linked issues, and milestones for all 3 parts:
MVP 1 Root - #6 
MVP 2 Root - #13
MVP 3 Root - #24

This issue is ready to close pending your final approval @Bubbus.

**Comment by Bubbus** [comment]
lets get this bread 🍞
