### ISSUE TITLE
Review working processes

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/CA-Halloween-2021#4]
I've put some paragraphs into the wiki to describe working processes that I think will help us manage the project.  Take a look at them and let me know if you agree with them or want to change anything.  We won't begin properly until we're happy with the way we'll approach this.  Let's not mark this as resolved until we have a two-way signoff.

https://github.com/Bubbus/CA-Halloween-2021#readme
https://github.com/Bubbus/CA-Halloween-2021/wiki - "General Notes"
https://github.com/Bubbus/CA-Halloween-2021/wiki/MVP---Iteration-flow

**Comment by dgibso29** [comment]
Everything looks good here, nice and structured to keep us from shooting ourselves in the foot.

Repo setup is a cool little thing. Turns out you can have multiple repo instances with GitHub Desktop & give them aliases -- I'm sure this is also a thing with CLI Git but still cool that the GUI allows it:
![image](https://user-images.githubusercontent.com/22088666/132112645-02447b93-444b-43c6-bdf4-83c683067ea5.png)
Didn't know you could do that so this will be a cool little workflow.

Approved by me - @Bubbus you're up.

**Comment by Bubbus** [comment]
we good here
